export const colors = {
    "#7FFFD4": "Água-marinha",
    "#66CDAA": "Água-marinha média",
    "#FFFF00": "Amarelo",
    "#FFFFE0": "Amarelo claro",
    "#ADFF2F": "Amarelo esverdeado",
    "#FAFAD2": "Amarelo ouro claro",
    "#DDA0DD": "Ameixa",
    "#FFEBCD": "Amêndoa",
    "#0000FF": "Azul",
    "#F0F8FF": "Azul alice",
    "#6A5ACD": "Azul ardósia",
    "#483D8B": "Azul ardósia escuro",
    "#4682B4": "Azul aço",
    "#B0C4DE": "Azul aço claro",
    "#5F9EA0": "Azul cadete",
    "#F0FFFF": "Azul celeste",
    "#ADD8E6": "Azul claro",
    "#87CEEB": "Azul céu",
    "#87CEFA": "Azul céu claro",
    "#00BFFF": "Azul céu profundo",
    "#00008B": "Azul escuro",
    "#6495ED": "Azul flor de milho",
    "#1E90FF": "Azul furtivo",
    "#191970": "Azul meia-noite",
    "#0000CD": "Azul médio",
    "#B0E0E6": "Azul pólvora",
    "#4169e1": "Azul real",
    "#8A2BE2": "Azul violeta",
    "#F5F5DC": "Bege",
    "#800000": "Bordô",
    "#FFFFFF": "Branco",
    "#FAEBD7": "Branco antigo",
    "#F8F8FF": "Branco fantasma",
    "#FFFAF0": "Branco floral",
    "#FFDEAD": "Branco navajo",
    "#F0E68C": "Caqui",
    "#D8BFD8": "Cardo",
    "#DC143C": "Carmesim",
    "#8B0000": "Castanho avermelhado",
    "#D2B48C": "Castanho claro",
    "#D2691E": "Chocolate",
    "#00FFFF": "Ciano",
    "#E0FFFF": "Ciano claro",
    "#008B8B": "Ciano escuro",
    "#808080": "Cinza",
    "#708090": "Cinza ardósia",
    "#778899": "Cinza ardósia claro",
    "#2F4F4F": "Cinza ardósia escuro",
    "#D3D3D3": "Cinza claro",
    "#A9A9A9": "Cinza escuro",
    "#696969": "Cinza fosco",
    "#DCDCDC": "Cinza médio",
    "#FFF5EE": "Concha",
    "#FF7F50": "Coral",
    "#F08080": "Coral claro",
    "#FFE4C4": "Creme de marisco",
    "#F5FFFA": "Creme de menta",
    "#BDB76B": "Caqui escuro",
    "#DAA520": "Dourado",
    "#B8860B": "Dourado escuro",
    "#EEE8AA": "Dourado pálido",
    "#FF00FF": "Fúchsia",
    "#2E8B57": "Herbal",
    "#4B0082": "Índigo",
    "#FF4500": "Jambo",
    "#FFA500": "Laranja",
    "#FF8C00": "Laranja escuro",
    "#E6E6FA": "Lavanda",
    "#FFF0F5": "Lavanda avermelhada",
    "#00FF00": "Lima",
    "#FAF0E6": "Linho",
    "#DEB887": "Madeira",
    "#8B008B": "Magenta escuro",
    "#FFEFD5": "Mamão batido",
    "#F0FFF0": "Maná",
    "#FFFFF0": "Marfim",
    "#F4A460": "Marrom amarelado",
    "#A52A2A": "Marrom claro",
    "#BC8F8F": "Marrom rosado",
    "#8B4513": "Marrom sela",
    "#FFF8DC": "Milho claro",
    "#FFE4B5": "Mocassim",
    "#000080": "Naval",
    "#FFFAFA": "Neve",
    "#808000": "Oliva",
    "#556B2F": "Oliva escura",
    "#6B8E23": "Oliva parda",
    "#DA70D6": "Orquídea",
    "#9932CC": "Orquídea escura",
    "#BA55D3": "Orquídea média",
    "#FFD700": "Ouro",
    "#CD853F": "Pardo",
    "#C0C0C0": "Prata",
    "#000000": "Preto",
    "#FFDAB9": "Pêssego",
    "#800080": "Púrpura",
    "#9370DB": "Púrpura média",
    "#FDF5E6": "Renda antiga",
    "#FFC0CB": "Rosa",
    "#FFE4E1": "Rosa embaçado",
    "#FF69B4": "Rosa forte",
    "#FF1493": "Rosa profundo",
    "#fa8072": "Salmão",
    "#FFA07A": "Salmão claro",
    "#E9967A": "Salmão escuro",
    "#FF8247": "Siena",
    "#B22222": "Tijolo refratário",
    "#FF6347": "Tomate",
    "#F5DEB3": "Trigo",
    "#00CED1": "Turquesa escura",
    "#48D1CC": "Turquesa média",
    "#AFEEEE": "Turquesa pálida",
    "#008000": "Verde",
    "#9ACD32": "Verde amarelado",
    "#90EE90": "Verde claro",
    "#006400": "Verde escuro",
    "#228B22": "Verde floresta",
    "#32CD32": "Verde lima",
    "#7CFC00": "Verde grama",
    "#20B2AA": "Verde mar claro",
    "#8FBC8F": "Verde mar escuro",
    "#7FFF00": "Verde Paris",
    "#00FF7F": "Verde primavera",
    "#00FA9A": "Verde primavera médio",
    "#98FB98": "Verde pálido",
    "#008080": "Verde-azulado",
    "#FF0000": "Vermelho",
    "#CD5C5C": "Vermelho indiano",
    "#C71585": "Vermelho violeta médio",
    "#DB7093": "Vermelho violeta pálido",
    "#EE82EE": "Violeta",
    "#9400D3": "Violeta escuro",
}

export function getColorName(rgb) {
    return colors[rgb];
}